In [1]:
# берем тестовые данные из версии 5 и перефразируем часть текстов, чтобы оценить результаты классификации на измененных данных

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("display.max_colwidth", None)


X_test = pd.read_csv("X_test_balanced.csv",index_col=0)
y_test = pd.read_csv("y_test_balanced.csv",index_col=0)

In [ ]:
test = X_test.merge(y_test, left_index=True, right_index=True, how='inner')
print(len(test),
      test.isna().sum())

900 text                  0
universal_category    0
dtype: int64

In [17]:
test = test.sort_values(by='universal_category').reset_index()
test.head()

,index,text,universal_category
0,0,назначение платежа: Перечисление средств по соглашению №2140 о предоставлении гранта победителю конкурса на предоставление грантов Раиса РТ на развитие гражданского общества от 26.11.2024г. НДС не облагается.\nназвание статьи: Гранты\nназвание проекта: Донорство в Татарстане\nкатегория донора: отсутствует,гранты субсидии конкурсы
1,180,назначение платежа: субсидия за февраль 2025\nназвание статьи: Соц.дем.\nназвание проекта: Присмотр и уход\nкатегория донора: отсутствует,гранты субсидии конкурсы
2,179,назначение платежа: (93810061540906600633246=2220593;02452000150)Субс-я на фин. обеспеч-е затрат соц. ориентир. некомер. организ-и в 2022 единовременно в соответ-и с граф-м перечисл. согл-е NГ-22 от 01.04.2022г. Без НДС\nназвание статьи: Грант\nназвание проекта: Станем сильнее вместе\nкатегория донора: Грант губернатора ЛО-2022-2023,гранты субсидии конкурсы
3,178,назначение платежа: Перечисление средств для открытия депозита по депозитной сделке № UNV-0000001249512 от 18.03.2024 согласно заявлению клиента. НДС не предусмотрен.\nназвание статьи: Грант\nназвание проекта: игрец\nкатегория донора: средние,гранты субсидии конкурсы
4,866,назначение платежа: Перечисление пожертвования по договору № Т-Гранты/НКО-25-000912 от 01.09.2025.НДС не облагается.\nназвание статьи: Гранты\nназвание проекта: Административные расходы\nкатегория донора: Девелопмент Групп,гранты субсидии конкурсы

In [18]:
test.to_csv("test.csv")

Далее в ручном режиме в тестовом наборе каждые первые 50 строк каждой сотни были скорректированы в части названий статей, проектов, доноров, после чего разделены по признакам для отправки в LLM.

In [22]:
test_corr = pd.read_csv('test_corr.csv', index_col=0)

In [23]:
test_corr.head()

,index,text,universal_category
0,0,назначение платежа: Перечисление средств по соглашению №2140 о предоставлении гранта победителю конкурса на предоставление грантов Раиса РТ на развитие гражданского общества от 26.11.2024г. НДС не облагается.\nназвание статьи: Грантик\nназвание проекта: Донорство в Татарстане\nкатегория донора: отсутствует,гранты субсидии конкурсы
1,180,назначение платежа: субсидия за февраль 2025\nназвание статьи: Социальная дем.\nназвание проекта: Присмотр и уход\nкатегория донора: отсутствует,гранты субсидии конкурсы
2,179,назначение платежа: (93810061540906600633246=2220593;02452000150)Субс-я на фин. обеспеч-е затрат соц. ориентир. некомер. организ-и в 2022 единовременно в соответ-и с граф-м перечисл. согл-е NГ-22 от 01.04.2022г. Без НДС\nназвание статьи: Гран\nназвание проекта: Станем сильнее вместе\nкатегория донора: Гран губернатора ЛО-2022-2023,гранты субсидии конкурсы
3,178,назначение платежа: Перечисление средств для открытия депозита по депозитной сделке № UNV-0000001249512 от 18.03.2024 согласно заявлению клиента. НДС не предусмотрен.\nназвание статьи: гранти\nназвание проекта: игрец\nкатегория донора: средние,гранты субсидии конкурсы
4,866,назначение платежа: Перечисление пожертвования по договору № Т-Гранты/НКО-25-000912 от 01.09.2025.НДС не облагается.\nназвание статьи: Гран\nназвание проекта: Административные расходы\nкатегория донора: Девелопмент Групп,гранты субсидии конкурсы

In [24]:
X_test_corr = test_corr['text']
y_test_corr = test_corr['universal_category']

In [27]:
X_test_corr.to_csv("X_test_corr.csv")
y_test_corr.to_csv("y_test_corr.csv")